import { families, metals, cuts, stones, carats, formatCt } from '@/lib/catalog';
import Icon from './Icon';
function Section({ n, label, extra, children }) { return <section className="control-section"><div className="section-label"><span><span className="step">{String(n).padStart(2, '0')}</span>{label}</span>{extra && <small>{extra}</small>}</div>{children}</section>; }
function Option({ field, value, state, choose, children }) { return <button className={`option ${state[field] === value ? 'active' : ''}`} aria-pressed={state[field] === value} onClick={() => choose(field, value)}>{children}</button>; }
export default function Controls({ state, choose }) {
    let n = 1;
    const plain = state.family === 'band' && state.model === 'plain';
    const option = (field, value, label) => <Option key={value} {...{ field, value, state, choose }}>{label}</Option>;
    return <div id="config-controls">
 <Section n={n++} label="O modelo"><div className="options">{Object.entries(families[state.family].models).map(([id, label]) => option('model', id, label))}</div></Section>
 <Section n={n++} label="O metal" extra="18k"><div className="metal-options">{Object.entries(metals).map(([id, m]) => <button key={id} className={`metal-option ${state.metal === id ? 'active' : ''}`} aria-pressed={state.metal === id} onClick={() => choose('metal', id)}><i className="swatch" style={{ background: m.css }}/>{m.label}</button>)}</div></Section>
 {!plain ? <><Section n={n++} label="A lapidação"><div className="options">{Object.entries(cuts).map(([id, label]) => <button key={id} className={`shape-option ${state.cut === id ? 'active' : ''}`} aria-pressed={state.cut === id} onClick={() => choose('cut', id)}><Icon name={id}/>{label}</button>)}</div></Section>
 {state.model !== 'rainbow' && <Section n={n++} label="A pedra"><div className="stone-selector">{Object.entries(stones).map(([id, s]) => <button key={id} className={`stone-dot ${state.stone === id ? 'active' : ''}`} aria-label={s.name} aria-pressed={state.stone === id} title={s.name} onClick={() => choose('stone', id)}><i style={{ background: s.swatch }}/></button>)}</div><p className="stone-name">{stones[state.stone].name}</p></Section>}
 <Section n={n++} label={state.family === 'ring' ? 'O tamanho da pedra' : 'O tamanho das pedras'}><div className="size-line"><strong>{formatCt(state.carat)}</strong><small>Escala visual aproximada</small></div><input type="range" min="0" max="6" step="1" value={carats.indexOf(state.carat)} aria-label="Tamanho da pedra em quilates" aria-valuetext={formatCt(state.carat)} onChange={e => choose('carat', carats[Number(e.target.value)])}/><div className="range-labels"><span>0,30 ct</span><span>1,00 ct</span><span>3,00 ct</span></div></Section>
 {state.family === 'ring' && <Section n={n++} label="Os detalhes"><div className="options">{option('halo', 'none', 'Sem contorno')}{option('halo', 'single', 'Ilusion')}{option('halo', 'double', 'Duplo')}</div><div className="options" style={{ marginTop: 8 }}>{option('bandStyle', 'plain', 'Aro liso')}{option('bandStyle', 'pave', 'Aro cravejado')}</div></Section>}</> : <><Section n={n++} label="A largura"><div className="size-line"><strong>{state.width} mm</strong></div><input type="range" min="3" max="7" value={state.width} aria-label="Largura da aliança em milímetros" onChange={e => choose('width', Number(e.target.value))}/><div className="range-labels"><span>3 mm</span><span>7 mm</span></div></Section><Section n={n++} label="O acabamento"><div className="options">{option('finish', 'polished', 'Polido')}{option('finish', 'matte', 'Acetinado')}</div></Section></>}
 </div>;
}
